const productsArray = [{id:"1",
    title:"Sambar Powder",
    category: "powder",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"450"}, {id:"2",
    title:"Rasam Powder",
    category: "powder",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"80"}, {id:"3",
    title:"Besan Laddoo",
    category: "box",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"300"}, {id:"4",
    title:"Gulab Jamun",
    category: "box",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"170"}, {id:"5",
    title:"Sambar Powder",
    category: "powder",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"450"}, {id:"6",
    title:"Rasam Powder",
    category: "powder",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"80"}, {id:"7",
    title:"Besan Laddoo",
    category: "box",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"300"}, {id:"8",
    title:"Gulab Jamun",
    category: "box",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"170"}, {id:"9",
    title:"Sambar Powder",
    category: "powder",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"450"}, {id:"10",
    title:"Rasam Powder",
    category: "powder",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"80"}, {id:"11",
    title:"Besan Laddoo",
    category: "box",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"300"}, {id:"12",
    title:"Gulab Jamun",
    category: "box",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"170"}, {id:"13",
    title:"Sambar Powder",
    category: "powder",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"450"}, {id:"14",
    title:"Rasam Powder",
    category: "powder",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"80"}, {id:"15",
    title:"Besan Laddoo",
    category: "box",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"300"}, {id:"16",
    title:"Gulab Jamun",
    category: "box",
    image:"https://m.media-amazon.com/images/I/717Ak2hi0NL._AC_UL480_QL65_.jpg",
    price:"170"}]

export default productsArray;
